site_name: Image Downloader
repo_url: https://github.com/bugfishtm/bugfish-image-downloader
repo_name: bugfish-image-downloader

nav:
  - Introduction: index.md
  - Download: download.md
  - Support: support.md
  - License: license.md
  - Impressum: https://bugfishtm.blogspot.com/2023/05/impressum.html
  - Privacy: https://bugfishtm.blogspot.com/2023/05/privacy.html
  - More by Bugfish: https://bugfishtm.github.io
 
theme:
  name: material
  logo: ./logo.png
  favicon: ./favicon.ico
  primary: deep orange
  language: 'en'
  accent: deep orange
  font: false
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
    - mkdocstrings
    - search
    - mkdocs-video
    - glightbox
    
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
use_directory_urls: false

extra:
  meta:
    author: "Jan-Maurice Dahlmanns"